<?php

namespace Database\Seeders;

use App\Models\Disease;
use Illuminate\Database\Seeder;

class DiseasesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $diseases = [
            // Canine Diseases
            'Parvoviral Infection',
            'Canine Distemper',
            'Canine Parainfluenza',
            'Canine Adenovirus',
            'Canine Coronavirus',
            'Canine Herpesvirus',
            'Canine Influenza',
            'Rabies',
            'Leptospirosis',
            'Lyme Disease',
            'Ehrlichiosis',
            'Anaplasmosis',
            'Rocky Mountain Spotted Fever',
            'Heartworm Disease',
            'Hookworm Infection',
            'Roundworm Infection',
            'Whipworm Infection',
            'Tapeworm Infection',
            'Giardiasis',
            'Coccidiosis',
            'Toxoplasmosis',
            'Demodectic Mange',
            'Sarcoptic Mange',
            'Ear Mites',
            'Fleas',
            'Ticks',
            'Atopic Dermatitis',
            'Food Allergy',
            'Contact Dermatitis',
            'Pyoderma',
            'Hot Spots',
            'Seborrhea',
            'Alopecia',
            'Hypothyroidism',
            'Hyperthyroidism',
            'Diabetes Mellitus',
            'Cushing\'s Disease',
            'Addison\'s Disease',
            'Pancreatitis',
            'Gastritis',
            'Enteritis',
            'Colitis',
            'Inflammatory Bowel Disease',
            'Gastric Dilatation-Volvulus',
            'Hepatitis',
            'Liver Disease',
            'Kidney Disease',
            'Urinary Tract Infection',
            'Bladder Stones',
            'Kidney Stones',
            'Prostatitis',
            'Pyometra',
            'Mastitis',
            'Ovarian Cysts',
            'Testicular Tumors',
            'Arthritis',
            'Hip Dysplasia',
            'Elbow Dysplasia',
            'Osteoarthritis',
            'Rheumatoid Arthritis',
            'Intervertebral Disc Disease',
            'Spinal Cord Injury',
            'Epilepsy',
            'Seizures',
            'Meningitis',
            'Encephalitis',
            'Brain Tumor',
            'Congestive Heart Failure',
            'Dilated Cardiomyopathy',
            'Hypertrophic Cardiomyopathy',
            'Mitral Valve Disease',
            'Arrhythmia',
            'Anemia',
            'Thrombocytopenia',
            'Hemophilia',
            'Von Willebrand Disease',
            'Pneumonia',
            'Bronchitis',
            'Asthma',
            'Collapsed Trachea',
            'Pulmonary Edema',
            'Pleural Effusion',
            'Eye Infections',
            'Conjunctivitis',
            'Keratitis',
            'Cataracts',
            'Glaucoma',
            'Retinal Detachment',
            'Dry Eye',
            'Ear Infections',
            'Otitis Externa',
            'Otitis Media',
            'Otitis Interna',
            'Dental Disease',
            'Gingivitis',
            'Periodontitis',
            'Tooth Abscess',
            'Oral Tumors',
            'Skin Cancer',
            'Mast Cell Tumor',
            'Lymphoma',
            'Osteosarcoma',
            'Hemangiosarcoma',
            'Melanoma',
            'Fibrosarcoma',
            'Lipoma',
            'Obesity',
            'Malnutrition',
            'Vitamin Deficiencies',
            'Poisoning',
            'Heat Stroke',
            'Hypothermia',
            'Frostbite',
            'Burns',
            'Wounds',
            'Abscesses',
            'Cellulitis',
            'Sepsis',
            'Shock',
            'Dehydration',
            'Electrolyte Imbalance',
            
            // Feline Diseases
            'Feline Panleukopenia',
            'Feline Calicivirus',
            'Feline Herpesvirus',
            'Feline Leukemia Virus',
            'Feline Immunodeficiency Virus',
            'Feline Infectious Peritonitis',
            'Feline Upper Respiratory Infection',
            'Feline Lower Urinary Tract Disease',
            'Feline Urethral Obstruction',
            'Feline Hyperthyroidism',
            'Feline Diabetes',
            'Feline Chronic Kidney Disease',
            'Feline Asthma',
            'Feline Infectious Anemia',
            'Feline Chlamydiosis',
            'Feline Bordetella',
            'Feline Toxoplasmosis',
            'Feline Ringworm',
            'Feline Acne',
            'Feline Eosinophilic Granuloma',
            'Feline Stomatitis',
            'Feline Gingivitis',
            'Feline Periodontal Disease',
            'Feline Resorptive Lesions',
            'Feline Cardiomyopathy',
            'Feline Hypertrophic Cardiomyopathy',
            'Feline Dilated Cardiomyopathy',
            'Feline Restrictive Cardiomyopathy',
            'Feline Heartworm Disease',
            'Feline Ear Mites',
            'Feline Flea Allergy Dermatitis',
            'Feline Food Allergy',
            'Feline Atopic Dermatitis',
            'Feline Pyoderma',
            'Feline Alopecia',
            'Feline Psychogenic Alopecia',
            'Feline Hyperesthesia Syndrome',
            'Feline Lower Urinary Tract Disease',
            'Feline Idiopathic Cystitis',
            'Feline Polycystic Kidney Disease',
            'Feline Hepatic Lipidosis',
            'Feline Inflammatory Bowel Disease',
            'Feline Pancreatitis',
            'Feline Lymphoma',
            'Feline Mammary Tumors',
            'Feline Squamous Cell Carcinoma',
            'Feline Fibrosarcoma',
            'Feline Injection Site Sarcoma',
            'Feline Obesity',
            'Feline Hepatic Disease',
            'Feline Renal Failure',
            'Feline Urinary Blockage',
            
            // Avian Diseases
            'Avian Influenza',
            'Newcastle Disease',
            'Psittacosis',
            'Avian Pox',
            'Aspergillosis',
            'Candidiasis',
            'Trichomoniasis',
            'Giardiasis in Birds',
            'Feather Plucking',
            'Avian Polyomavirus',
            'Pacheco\'s Disease',
            'Avian Tuberculosis',
            'Bumblefoot',
            'Egg Binding',
            'Avian Gout',
            'Avian Fatty Liver Disease',
            'Avian Respiratory Disease',
            'Avian Chlamydiosis',
            
            // Equine Diseases
            'Equine Influenza',
            'Equine Herpesvirus',
            'Equine Encephalomyelitis',
            'West Nile Virus',
            'Tetanus',
            'Strangles',
            'Potomac Horse Fever',
            'Equine Infectious Anemia',
            'Equine Protozoal Myeloencephalitis',
            'Equine Colic',
            'Laminitis',
            'Navicular Disease',
            'Tendonitis',
            'Bowed Tendon',
            'Splints',
            'Ringbone',
            'Sidebone',
            'Osteoarthritis in Horses',
            'Equine Cushing\'s Disease',
            'Equine Metabolic Syndrome',
            'Equine Asthma',
            'Recurrent Airway Obstruction',
            'Equine Gastric Ulcer Syndrome',
            'Equine Colitis',
            'Equine Skin Conditions',
            'Rain Rot',
            'Scratches',
            'Sweet Itch',
            'Equine Sarcoids',
            'Melanoma in Horses',
            'Equine Wobblers Syndrome',
            'Equine Motor Neuron Disease',
            'Equine Polysaccharide Storage Myopathy',
            'Tying Up',
            'Exertional Rhabdomyolysis',
            'Equine Protozoal Myeloencephalitis',
            'Equine Protozoal Myeloencephalitis',
            
            // Bovine Diseases
            'Bovine Respiratory Disease',
            'Bovine Viral Diarrhea',
            'Infectious Bovine Rhinotracheitis',
            'Foot and Mouth Disease',
            'Brucellosis',
            'Tuberculosis',
            'Mastitis',
            'Metritis',
            'Retained Placenta',
            'Ketosis',
            'Milk Fever',
            'Grass Tetany',
            'Bloat',
            'Acidosis',
            'Displaced Abomasum',
            'Hardware Disease',
            'Johnes Disease',
            'Blackleg',
            'Anthrax',
            'Bovine Spongiform Encephalopathy',
            'Bovine Leukosis',
            'Bovine Papillomatosis',
            'Bovine Dermatitis',
            'Bovine Foot Rot',
            'Bovine Digital Dermatitis',
            'Bovine Laminitis',
            'Bovine Ketosis',
            'Bovine Fatty Liver',
            'Bovine Pneumonia',
            'Bovine Pleurisy',
            
            // Small Mammal Diseases
            'Dental Malocclusion in Rabbits',
            'Gastrointestinal Stasis',
            'Snuffles',
            'Pasteurellosis',
            'Myxomatosis',
            'Rabbit Hemorrhagic Disease',
            'Ear Mites in Rabbits',
            'Flystrike',
            'Urinary Calculi',
            'Respiratory Infections',
            'Skin Conditions',
            'Obesity in Small Mammals',
            'Diabetes in Guinea Pigs',
            'Scurvy',
            'Dental Disease in Rodents',
            'Tumors in Small Mammals',
            'Abscesses in Small Mammals',
            'Parasitic Infections',
            
            // Reptile Diseases
            'Metabolic Bone Disease',
            'Respiratory Infections',
            'Dysecdysis',
            'Stomatitis',
            'Abscesses',
            'Parasitic Infections',
            'Impaction',
            'Dysecdysis',
            'Thermal Burns',
            'Shell Rot',
            'Vitamin A Deficiency',
            'Hypovitaminosis A',
            'Hypervitaminosis A',
            'Gout',
            'Septicemia',
            'Pneumonia',
            'Egg Binding',
            'Dystocia',
            
            // General/Common
            'Parasitic Infestation',
            'Bacterial Infection',
            'Viral Infection',
            'Fungal Infection',
            'Protozoal Infection',
            'Trauma',
            'Fractures',
            'Lacerations',
            'Bite Wounds',
            'Foreign Body Ingestion',
            'Toxicosis',
            'Anaphylaxis',
            'Allergic Reactions',
            'Autoimmune Disorders',
            'Immune-mediated Diseases',
            'Neoplasia',
            'Cancer',
            'Tumors',
            'Cysts',
            'Abscesses',
            'Cellulitis',
            'Sepsis',
            'Shock',
            'Dehydration',
            'Malnutrition',
            'Cachexia',
            'Failure to Thrive',
            'Weakness',
            'Lethargy',
            'Anorexia',
            'Polyphagia',
            'Polydipsia',
            'Polyuria',
            'Dysuria',
            'Hematuria',
            'Dyspnea',
            'Coughing',
            'Sneezing',
            'Nasal Discharge',
            'Ocular Discharge',
            'Vomiting',
            'Diarrhea',
            'Constipation',
            'Abdominal Pain',
            'Lameness',
            'Stiffness',
            'Seizures',
            'Tremors',
            'Ataxia',
            'Paralysis',
            'Behavioral Changes',
            'Aggression',
            'Anxiety',
            'Depression',
        ];

        foreach ($diseases as $diseaseName) {
            Disease::firstOrCreate(
                ['name' => $diseaseName],
                [
                    'symptoms' => null,
                    'home_remedy' => null,
                ]
            );
        }

        $this->command->info('Seeded ' . count($diseases) . ' diseases.');
    }
}













