<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { Head, Form, router } from '@inertiajs/vue3';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { SearchableSelect } from '@/components/ui/searchable-select';
import InputError from '@/components/InputError.vue';
import LocationMapPicker from '@/components/LocationMapPicker.vue';
import { UserPlus, ArrowLeft, Search, User, Dog, CheckCircle, Loader2, Plus, Trash2 } from 'lucide-vue-next';
import { Link } from '@inertiajs/vue3';
import { dashboard } from '@/routes';
import { ref, computed, watch } from 'vue';
import axios from 'axios';

interface PetType {
    id: number;
    name: string;
}

interface FoundPet {
    id: number;
    pet_name: string;
    pet_breed: string;
    pet_gender: string | null;
    pet_birth_date: string | null;
    pet_allergies: string | null;
    pet_type: {
        id: number;
        name: string;
    };
    owner: {
        id: number;
        name: string;
        first_name: string | null;
        last_name: string | null;
        email: string;
        mobile_number: string | null;
        address: string | null;
        lat: number | null;
        lng: number | null;
    } | null;
}

interface AppointmentType {
    id: number;
    name: string;
}

interface Props {
    pet_types: PetType[];
    pet_breeds: Record<string, string[]>;
    appointment_types: AppointmentType[];
}

const props = defineProps<Props>();

const breadcrumbs = [
    { title: 'Dashboard', href: dashboard().url },
    { title: 'Walk-In Clients', href: '/admin/walk_in_clients' },
    { title: 'Create Walk-In Client', href: '#' },
];

const location = ref<{ lat: number | null; lng: number | null } | null>(null);
const currentStep = ref<'search' | 'form' | 'visitDetails'>('search');
const searchPetName = ref('');
const foundPets = ref<FoundPet[]>([]);
const isSearching = ref(false);
const searchError = ref<string | null>(null);

// Multiple pets management
interface PetFormData {
    pet_type_id: string;
    custom_pet_type_name: string;
    pet_name: string;
    pet_breed: string;
    custom_pet_breed_name: string;
    pet_gender: string;
    pet_birth_date: string;
    pet_allergies: string;
    customPetTypeDisplay: string | null;
    customBreedDisplay: string | null;
}

const pets = ref<PetFormData[]>([]);
const petErrors = ref<Record<number, Record<string, string>>>({});

// Visit details - checkbox selections
interface PetAppointmentSelections {
    [petIndex: string]: string[]; // petIndex -> appointment_type_ids[]
}

const visitDetailsSelections = ref<PetAppointmentSelections>({});
const symptoms = ref('');

// Email lookup state
const isLookingUpEmail = ref(false);
const emailLookupResult = ref<'found' | 'not_found' | null>(null);
const emailLookupTimeout = ref<ReturnType<typeof setTimeout> | null>(null);

// Track if existing pet was selected
const existingPetSelected = ref(false);

// Store existing pet/owner display info
const existingOwnerInfo = ref<{
    name: string;
    email: string;
    mobile_number: string | null;
    address: string | null;
} | null>(null);

const existingPetInfo = ref<{
    pet_name: string;
    pet_type: string;
    pet_breed: string;
    pet_gender: string | null;
    pet_birth_date: string | null;
    pet_allergies: string | null;
} | null>(null);

// Key to force LocationMapPicker re-initialization
const mapKey = ref(0);

const form = router.form({
    // Existing records (when using registered pet/owner)
    existing_owner_id: null as number | null,
    existing_pet_id: null as number | null,
    // Client fields (for new clients)
    first_name: '',
    last_name: '',
    name: '',
    email: '',
    mobile_number: '',
    address: '',
    lat: null as number | null,
    lng: null as number | null,
});

// Initialize with one empty pet
const initializePet = (): PetFormData => ({
    pet_type_id: '',
    custom_pet_type_name: '',
    pet_name: '',
    pet_breed: '',
    custom_pet_breed_name: '',
    pet_gender: '',
    pet_birth_date: '',
    pet_allergies: '',
    customPetTypeDisplay: null,
    customBreedDisplay: null,
});

// Initialize with one pet
if (pets.value.length === 0) {
    pets.value.push(initializePet());
}

// Track the last auto-generated full name to detect manual edits
const lastAutoGeneratedName = ref('');

// Handle creating a new pet type
const handleCreatePetType = (petIndex: number, name: string) => {
    pets.value[petIndex].custom_pet_type_name = name;
    pets.value[petIndex].customPetTypeDisplay = name;
};

// Handle creating a new breed
const handleCreateBreed = (petIndex: number, name: string) => {
    pets.value[petIndex].custom_pet_breed_name = name;
    pets.value[petIndex].customBreedDisplay = name;
};

// Add a new pet
const addPet = () => {
    pets.value.push(initializePet());
};

// Remove a pet
const removePet = (index: number) => {
    if (pets.value.length > 1) {
        pets.value.splice(index, 1);
        // Clean up visit details selections for removed pet
        delete visitDetailsSelections.value[index.toString()];
        // Reindex remaining selections
        const newSelections: PetAppointmentSelections = {};
        Object.keys(visitDetailsSelections.value).forEach((key) => {
            const oldIndex = parseInt(key);
            if (oldIndex > index) {
                newSelections[(oldIndex - 1).toString()] = visitDetailsSelections.value[key];
            } else if (oldIndex < index) {
                newSelections[key] = visitDetailsSelections.value[key];
            }
        });
        visitDetailsSelections.value = newSelections;
    }
};

// Get breed options for a specific pet
const getBreedOptions = (petIndex: number) => {
    const pet = pets.value[petIndex];
    const petTypeId = pet.pet_type_id;
    if (!petTypeId || petTypeId === '__new__') return [];
    
    const petType = props.pet_types.find(pt => pt.id.toString() === petTypeId);
    if (!petType || !props.pet_breeds[petType.name]) return [];
    
    return props.pet_breeds[petType.name].map(breed => ({
        value: breed,
        label: breed,
    }));
};

// Get selected pet type name for a specific pet
const getSelectedPetTypeName = (petIndex: number) => {
    const pet = pets.value[petIndex];
    if (!pet.pet_type_id) return null;
    const petType = props.pet_types.find(pt => pt.id.toString() === pet.pet_type_id);
    return petType?.name || null;
};

// Transform pet types for SearchableSelect
const petTypeOptions = computed(() => {
    return props.pet_types.map(pt => ({
        value: pt.id.toString(),
        label: pt.name,
    }));
});

// Transform appointment types for checkboxes
const appointmentTypeOptions = computed(() => {
    return props.appointment_types.map(type => ({
        value: type.id.toString(),
        label: type.name,
    }));
});

// Watch pet type changes to clear breed selection - watch each pet individually
const petWatchers = ref<Array<() => void>>([]);

// Setup watchers for pets when they change
watch(() => pets.value.length, () => {
    // Clean up old watchers
    petWatchers.value.forEach(cleanup => cleanup());
    petWatchers.value = [];
    
    // Setup new watchers for each pet
    pets.value.forEach((pet, index) => {
        const stop1 = watch(() => pet.pet_type_id, (newValue) => {
            pet.pet_breed = '';
            pet.custom_pet_breed_name = '';
            pet.customBreedDisplay = null;
            // Clear custom pet type when selecting an existing type
            if (newValue !== '__new__') {
                pet.custom_pet_type_name = '';
                pet.customPetTypeDisplay = null;
            }
        });
        
        const stop2 = watch(() => pet.pet_breed, (newValue) => {
            if (newValue !== '__new__') {
                pet.custom_pet_breed_name = '';
                pet.customBreedDisplay = null;
            }
        });
        
        petWatchers.value.push(() => {
            stop1();
            stop2();
        });
    });
}, { immediate: true });

// Auto-generate full name from first and last name
// Only auto-generate if name is empty or matches the expected auto-generated value
watch([() => form.first_name, () => form.last_name], () => {
    // Skip auto-generation if email lookup found a client (to preserve their existing name)
    if (emailLookupResult.value === 'found') {
        return;
    }
    
    // Skip auto-generation if existing pet/owner is selected
    if (existingPetSelected.value) {
        return;
    }
    
    const firstName = (form.first_name || '').trim();
    const lastName = (form.last_name || '').trim();
    const generatedName = [firstName, lastName].filter(Boolean).join(' ').trim();
    
    // Auto-generate if name is empty or matches the last auto-generated value
    if (!form.name || form.name === lastAutoGeneratedName.value) {
        form.name = generatedName;
        lastAutoGeneratedName.value = generatedName;
    } else {
        // Update the expected auto-generated name for future comparisons
        lastAutoGeneratedName.value = generatedName;
    }
});

// Email validation regex
const isValidEmail = (email: string) => {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
};

// Lookup client by email with debounce
const lookupClientByEmail = async (email: string) => {
    if (!email || !isValidEmail(email)) {
        emailLookupResult.value = null;
        return;
    }

    isLookingUpEmail.value = true;
    emailLookupResult.value = null;

    try {
        const response = await axios.post('/admin/walk_in_clients/lookup-by-email', { email });
        
        if (response.data.found && response.data.client) {
            const client = response.data.client;
            
            // Autofill form fields
            form.first_name = client.first_name || '';
            form.last_name = client.last_name || '';
            form.name = client.name || '';
            form.mobile_number = client.mobile_number || '';
            form.address = client.address || '';
            
            // Update location if available
            if (client.lat && client.lng) {
                location.value = { lat: client.lat, lng: client.lng };
                form.lat = client.lat;
                form.lng = client.lng;
            }
            
            // Reset auto-generated name tracking since we're using existing client data
            lastAutoGeneratedName.value = '';
            emailLookupResult.value = 'found';
        } else {
            emailLookupResult.value = 'not_found';
        }
    } catch (error) {
        console.error('Email lookup failed:', error);
        emailLookupResult.value = null;
    } finally {
        isLookingUpEmail.value = false;
    }
};

// Watch email field with debounce
watch(() => form.email, (newEmail) => {
    // Clear previous timeout
    if (emailLookupTimeout.value) {
        clearTimeout(emailLookupTimeout.value);
    }
    
    // Reset result when email changes
    emailLookupResult.value = null;
    // Reset auto-generated name tracking when email changes
    lastAutoGeneratedName.value = '';
    
    // Set new debounced timeout (500ms delay)
    emailLookupTimeout.value = setTimeout(() => {
        lookupClientByEmail(newEmail);
    }, 500);
});

// Visit details checkbox handlers
const toggleCheckbox = (petIndex: string, appointmentTypeId: string) => {
    if (!visitDetailsSelections.value[petIndex]) {
        visitDetailsSelections.value[petIndex] = [];
    }
    const index = visitDetailsSelections.value[petIndex].indexOf(appointmentTypeId);
    if (index > -1) {
        visitDetailsSelections.value[petIndex].splice(index, 1);
    } else {
        visitDetailsSelections.value[petIndex].push(appointmentTypeId);
    }
};

const isCheckboxSelected = (petIndex: string, appointmentTypeId: string): boolean => {
    return visitDetailsSelections.value[petIndex]?.includes(appointmentTypeId) || false;
};

// Check if at least one appointment type is selected for at least one pet
const canProceedToSubmit = computed(() => {
    if (existingPetSelected.value) {
        // For existing pet, check index '0'
        return visitDetailsSelections.value['0']?.length > 0 || false;
    }
    return Object.values(visitDetailsSelections.value).some(
        appointmentTypeIds => appointmentTypeIds.length > 0
    );
});

const updateLocation = (value: { lat: number | null; lng: number | null }) => {
    location.value = value;
    form.lat = value.lat;
    form.lng = value.lng;
};

const searchPets = async () => {
    if (!searchPetName.value.trim()) {
        searchError.value = 'Please enter a pet name to search.';
        return;
    }

    isSearching.value = true;
    searchError.value = null;
    foundPets.value = [];

    try {
        const response = await axios.post('/admin/walk_in_clients/search-pets', {
            pet_name: searchPetName.value.trim(),
        });

        foundPets.value = response.data.pets;
        
        if (foundPets.value.length === 0) {
            searchError.value = 'No pets found with that name. You can proceed to create a new client and pet.';
        }
    } catch (error: any) {
        searchError.value = error.response?.data?.message || 'An error occurred while searching for pets.';
    } finally {
        isSearching.value = false;
    }
};

const useExistingPet = (pet: FoundPet) => {
    // Mark existing pet as selected
    existingPetSelected.value = true;
    
    // Store existing IDs for the backend
    form.existing_pet_id = pet.id;
    
    if (pet.owner) {
        form.existing_owner_id = pet.owner.id;
        
        // Store owner display info
        existingOwnerInfo.value = {
            name: pet.owner.name,
            email: pet.owner.email,
            mobile_number: pet.owner.mobile_number,
            address: pet.owner.address,
        };
    }
    
    // Store pet display info
    existingPetInfo.value = {
        pet_name: pet.pet_name,
        pet_type: pet.pet_type.name,
        pet_breed: pet.pet_breed,
        pet_gender: pet.pet_gender,
        pet_birth_date: pet.pet_birth_date,
        pet_allergies: pet.pet_allergies,
    };
    
    // Reset auto-generated name tracking since we're using existing pet/owner
    lastAutoGeneratedName.value = '';
    
    // Clear pets array and add the existing pet info (for visit details step)
    pets.value = [];
    
    // Move to form step
    currentStep.value = 'form';
};

const continueToForm = () => {
    // Pre-fill pet name if searched
    if (searchPetName.value.trim() && pets.value.length > 0) {
        pets.value[0].pet_name = searchPetName.value.trim();
    }
    currentStep.value = 'form';
};

const goBackToSearch = () => {
    currentStep.value = 'search';
};

const goToVisitDetails = () => {
    // If using existing pet, skip validation and go directly to visit details
    if (existingPetSelected.value && existingPetInfo.value) {
        currentStep.value = 'visitDetails';
        return;
    }
    
    // Validate pets before proceeding
    let hasErrors = false;
    petErrors.value = {};
    
    if (pets.value.length === 0) {
        petErrors.value[0] = { pets: 'At least one pet is required' };
        hasErrors = true;
    }
    
    pets.value.forEach((pet, index) => {
        const errors: Record<string, string> = {};
        
        if (!pet.pet_type_id && !pet.custom_pet_type_name) {
            errors.pet_type_id = 'Pet type is required';
            hasErrors = true;
        }
        
        if (!pet.pet_breed && !pet.custom_pet_breed_name) {
            errors.pet_breed = 'Pet breed is required';
            hasErrors = true;
        }
        
        if (Object.keys(errors).length > 0) {
            petErrors.value[index] = errors;
        }
    });
    
    if (!hasErrors) {
        currentStep.value = 'visitDetails';
    }
};

const goBackToForm = () => {
    currentStep.value = 'form';
};

const submit = () => {
    // If using existing pet, use the existing flow
    if (existingPetSelected.value && form.existing_pet_id && form.existing_owner_id) {
        // For existing pet, we need to get appointment types from visit details
        // Since we only have one existing pet, use index 0
        const appointmentTypeIds = visitDetailsSelections.value['0'] || [];
        
        if (appointmentTypeIds.length === 0) {
            // Show error if no appointment types selected
            return;
        }
        
        // For existing pet, we'll create appointments for each selected type
        // But the backend expects a different format, so we'll need to handle this
        // For now, let's use the first appointment type and let backend handle multiple
        form.transform((data) => ({
            ...data,
            appointment_type_id: appointmentTypeIds[0],
            appointment_type_ids: appointmentTypeIds,
            symptoms: symptoms.value,
        })).post('/admin/walk_in_clients');
        return;
    }
    
    // Convert pets and visit details to the format expected by backend
    const petsData = pets.value.map((pet, index) => ({
        pet_type_id: pet.pet_type_id,
        custom_pet_type_name: pet.custom_pet_type_name || '',
        pet_name: pet.pet_name || '',
        pet_breed: pet.pet_breed || '',
        custom_pet_breed_name: pet.custom_pet_breed_name || '',
        pet_gender: pet.pet_gender || '',
        pet_birth_date: pet.pet_birth_date || '',
        pet_allergies: pet.pet_allergies || '',
        appointment_type_ids: visitDetailsSelections.value[index.toString()] || [],
    }));
    
    form.transform((data) => ({
        ...data,
        pets: petsData,
        symptoms: symptoms.value,
    })).post('/admin/walk_in_clients');
};
</script>

<template>
    <Head title="Create Walk-In Client" />

    <AppLayout :breadcrumbs="breadcrumbs">
        <div class="container mx-auto p-6 max-w-4xl">
            <Card>
                <CardHeader>
                    <div class="flex items-center gap-2">
                        <Link href="/admin/walk_in_clients">
                            <Button variant="ghost" size="sm">
                                <ArrowLeft class="h-4 w-4" />
                            </Button>
                        </Link>
                        <div>
                            <CardTitle class="flex items-center gap-2">
                                <UserPlus class="h-5 w-5" />
                                Create New Walk-In Client
                            </CardTitle>
                            <CardDescription>
                                <span v-if="currentStep === 'search'">
                                    Step 1: Search for an existing pet by name. If found, you can use the existing owner information.
                                </span>
                                <span v-else-if="currentStep === 'form'">
                                    Step 2: Complete the client and pet information to register.
                                </span>
                                <span v-else>
                                    Step 3: Select appointment types for each pet and add symptoms/notes.
                                </span>
                            </CardDescription>
                        </div>
                    </div>
                </CardHeader>
                <CardContent>
                    <!-- Step 1: Search for Pet -->
                    <div v-if="currentStep === 'search'" class="space-y-6">
                        <div class="space-y-4">
                            <div class="space-y-2">
                                <Label for="search_pet_name">Search Pet by Name <span class="text-destructive">*</span></Label>
                                <div class="flex gap-2">
                                    <Input
                                        id="search_pet_name"
                                        v-model="searchPetName"
                                        type="text"
                                        placeholder="Enter pet name (e.g., Max, Bella)"
                                        autocomplete="off"
                                        @keyup.enter="searchPets"
                                        class="flex-1"
                                    />
                                    <Button 
                                        type="button" 
                                        @click="searchPets" 
                                        :disabled="isSearching || !searchPetName.trim()"
                                    >
                                        <Search class="h-4 w-4 mr-2" />
                                        {{ isSearching ? 'Searching...' : 'Search' }}
                                    </Button>
                                </div>
                                <p class="text-xs text-muted-foreground">
                                    Enter the pet's name to search the database. If found, you'll see the pet and owner information.
                                </p>
                                <InputError v-if="searchError" :message="searchError" />
                            </div>

                            <!-- Display Found Pets -->
                            <div v-if="foundPets.length > 0" class="space-y-4">
                                <div class="border-t pt-4">
                                    <h3 class="text-lg font-semibold mb-4">Found Pets</h3>
                                    <div class="space-y-3">
                                        <Card 
                                            v-for="pet in foundPets" 
                                            :key="pet.id"
                                            class="cursor-pointer hover:bg-accent transition-colors"
                                        >
                                            <CardContent class="p-4">
                                                <div class="flex items-start justify-between">
                                                    <div class="flex-1">
                                                        <div class="flex items-center gap-2 mb-2">
                                                            <Dog class="h-5 w-5 text-primary" />
                                                            <h4 class="font-semibold text-lg">{{ pet.pet_name }}</h4>
                                                            <span class="text-sm text-muted-foreground">({{ pet.pet_type.name }})</span>
                                                        </div>
                                                        <div class="space-y-1 text-sm text-muted-foreground">
                                                            <p><span class="font-medium">Breed:</span> {{ pet.pet_breed }}</p>
                                                            <p v-if="pet.pet_gender"><span class="font-medium">Gender:</span> {{ pet.pet_gender }}</p>
                                                        </div>
                                                        <div v-if="pet.owner" class="mt-3 pt-3 border-t">
                                                            <div class="flex items-center gap-2 mb-2">
                                                                <User class="h-4 w-4 text-primary" />
                                                                <h5 class="font-semibold">Owner Information</h5>
                                                            </div>
                                                            <div class="space-y-1 text-sm text-muted-foreground">
                                                                <p><span class="font-medium">Name:</span> {{ pet.owner.name }}</p>
                                                                <p><span class="font-medium">Email:</span> {{ pet.owner.email }}</p>
                                                                <p v-if="pet.owner.mobile_number"><span class="font-medium">Mobile:</span> {{ pet.owner.mobile_number }}</p>
                                                                <p v-if="pet.owner.address"><span class="font-medium">Address:</span> {{ pet.owner.address }}</p>
                                                            </div>
                                                        </div>
                                                        <div v-else class="mt-3 pt-3 border-t">
                                                            <p class="text-sm text-muted-foreground">No owner information available</p>
                                                        </div>
                                                    </div>
                                                    <Button 
                                                        v-if="pet.owner"
                                                        @click="useExistingPet(pet)"
                                                        class="ml-4"
                                                    >
                                                        Use This Pet & Owner
                                                    </Button>
                                                </div>
                                            </CardContent>
                                        </Card>
                                    </div>
                                </div>
                            </div>

                            <!-- Continue to Form Button -->
                            <div class="flex justify-end gap-4 pt-4 border-t">
                                <Link href="/admin/walk_in_clients">
                                    <Button type="button" variant="outline">Cancel</Button>
                                </Link>
                                <Button 
                                    type="button" 
                                    @click="continueToForm"
                                    :disabled="isSearching"
                                >
                                    Continue to Registration Form
                                </Button>
                            </div>
                        </div>
                    </div>

                    <!-- Step 2: Registration Form -->
                    <Form v-if="currentStep === 'form'" @submit.prevent="goToVisitDetails" class="space-y-6">
                        <div class="flex items-center justify-between mb-4 pb-4 border-b">
                            <h3 class="text-lg font-semibold">Owner Information</h3>
                            <Button type="button" variant="ghost" size="sm" @click="goBackToSearch">
                                <ArrowLeft class="h-4 w-4 mr-2" />
                                Back to Search
                            </Button>
                        </div>

                        <!-- Existing Owner Display (Plain Text) -->
                        <div v-if="existingPetSelected && existingOwnerInfo" class="space-y-4">
                            <p class="text-xs text-green-600 flex items-center gap-1">
                                <CheckCircle class="h-3 w-3" />
                                Owner already registered in the system.
                            </p>
                            <div class="bg-muted/50 rounded-lg p-4 space-y-3">
                                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div>
                                        <p class="text-sm font-medium text-muted-foreground">Name</p>
                                        <p class="text-sm">{{ existingOwnerInfo.name }}</p>
                                    </div>
                                    <div>
                                        <p class="text-sm font-medium text-muted-foreground">Email</p>
                                        <p class="text-sm">{{ existingOwnerInfo.email }}</p>
                                    </div>
                                    <div>
                                        <p class="text-sm font-medium text-muted-foreground">Mobile Number</p>
                                        <p class="text-sm">{{ existingOwnerInfo.mobile_number || 'Not provided' }}</p>
                                    </div>
                                    <div>
                                        <p class="text-sm font-medium text-muted-foreground">Address</p>
                                        <p class="text-sm">{{ existingOwnerInfo.address || 'Not provided' }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- New Owner Form (Inputs) -->
                        <template v-else>
                            <div class="space-y-2">
                                <Label for="email">Email <span class="text-red-500">*</span></Label>
                                <div class="relative">
                                    <Input
                                        id="email"
                                        v-model="form.email"
                                        type="email"
                                        required
                                        autocomplete="email"
                                        :class="{ 'pr-10': isLookingUpEmail || emailLookupResult }"
                                    />
                                    <div v-if="isLookingUpEmail" class="absolute right-3 top-1/2 -translate-y-1/2">
                                        <Loader2 class="h-4 w-4 animate-spin text-muted-foreground" />
                                    </div>
                                    <div v-else-if="emailLookupResult === 'found'" class="absolute right-3 top-1/2 -translate-y-1/2">
                                        <CheckCircle class="h-4 w-4 text-green-500" />
                                    </div>
                                </div>
                                <p v-if="emailLookupResult === 'found'" class="text-xs text-green-600 flex items-center gap-1">
                                    <CheckCircle class="h-3 w-3" />
                                    Client found! Form has been auto-filled with existing information.
                                </p>
                                <p v-else class="text-xs text-muted-foreground">
                                    Enter an email to check if the client is already registered.
                                </p>
                                <InputError :message="form.errors.email" />
                            </div>

                            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                <div class="space-y-2">
                                    <Label for="first_name">First Name</Label>
                                    <Input
                                        id="first_name"
                                        v-model="form.first_name"
                                        type="text"
                                        autocomplete="given-name"
                                        :disabled="emailLookupResult === 'found'"
                                    />
                                    <InputError :message="form.errors.first_name" />
                                </div>

                                <div class="space-y-2">
                                    <Label for="last_name">Last Name</Label>
                                    <Input
                                        id="last_name"
                                        v-model="form.last_name"
                                        type="text"
                                        autocomplete="family-name"
                                        :disabled="emailLookupResult === 'found'"
                                    />
                                    <InputError :message="form.errors.last_name" />
                                </div>
                            </div>

                            <div class="space-y-2">
                                <Label for="name">Full Name <span class="text-muted-foreground text-xs">(optional, auto-generated if left blank)</span></Label>
                                <Input
                                    id="name"
                                    v-model="form.name"
                                    type="text"
                                    autocomplete="name"
                                    placeholder="Will be auto-generated from first and last name"
                                    :disabled="emailLookupResult === 'found'"
                                />
                                <InputError :message="form.errors.name" />
                            </div>

                            <div class="space-y-2">
                                <Label for="mobile_number">Mobile Number <span class="text-muted-foreground text-xs">(Philippine number)</span></Label>
                                <Input
                                    id="mobile_number"
                                    v-model="form.mobile_number"
                                    type="tel"
                                    autocomplete="tel"
                                    placeholder="09123456789 or +639123456789"
                                    :disabled="emailLookupResult === 'found'"
                                />
                                <p class="text-xs text-muted-foreground">Format: 09XX XXX XXXX or +639XX XXX XXXX</p>
                                <InputError :message="form.errors.mobile_number" />
                            </div>

                            <div class="space-y-2">
                                <Label for="address">Complete Address</Label>
                                <Input
                                    id="address"
                                    v-model="form.address"
                                    type="text"
                                    autocomplete="street-address"
                                    placeholder="Street, Barangay, City, Province"
                                    :disabled="emailLookupResult === 'found'"
                                />
                                <InputError :message="form.errors.address" />
                            </div>

                            <div v-if="emailLookupResult !== 'found'" class="space-y-2">
                                <Label>Location Pin</Label>
                                <p class="text-xs text-muted-foreground mb-2">Click on the map to set a location pin, or drag the pin to adjust its position.</p>
                                <LocationMapPicker
                                    :model-value="location"
                                    @update:model-value="updateLocation"
                                    height="400px"
                                />
                                <InputError :message="form.errors.lat" />
                                <InputError :message="form.errors.lng" />
                            </div>
                        </template>

                        <!-- Pet Information Section -->
                        <div class="border-t pt-6 mt-6">
                            <div class="flex items-center justify-between mb-4">
                                <h3 class="text-lg font-semibold">Pet Information</h3>
                                <Button type="button" variant="outline" size="sm" @click="addPet">
                                    <Plus class="h-4 w-4 mr-2" />
                                    Add Pet
                                </Button>
                            </div>
                            
                            <!-- Existing Pet Display (Plain Text) -->
                            <div v-if="existingPetSelected && existingPetInfo" class="space-y-4">
                                <p class="text-xs text-green-600 flex items-center gap-1">
                                    <CheckCircle class="h-3 w-3" />
                                    Pet already registered in the system.
                                </p>
                                <div class="bg-muted/50 rounded-lg p-4 space-y-3">
                                    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                                        <div>
                                            <p class="text-sm font-medium text-muted-foreground">Pet Name</p>
                                            <p class="text-sm">{{ existingPetInfo.pet_name || 'Not provided' }}</p>
                                        </div>
                                        <div>
                                            <p class="text-sm font-medium text-muted-foreground">Pet Type</p>
                                            <p class="text-sm">{{ existingPetInfo.pet_type }}</p>
                                        </div>
                                        <div>
                                            <p class="text-sm font-medium text-muted-foreground">Breed</p>
                                            <p class="text-sm">{{ existingPetInfo.pet_breed }}</p>
                                        </div>
                                        <div>
                                            <p class="text-sm font-medium text-muted-foreground">Gender</p>
                                            <p class="text-sm">{{ existingPetInfo.pet_gender || 'Not provided' }}</p>
                                        </div>
                                        <div>
                                            <p class="text-sm font-medium text-muted-foreground">Birth Date</p>
                                            <p class="text-sm">{{ existingPetInfo.pet_birth_date || 'Not provided' }}</p>
                                        </div>
                                    </div>
                                    <div v-if="existingPetInfo.pet_allergies">
                                        <p class="text-sm font-medium text-muted-foreground">Allergies</p>
                                        <p class="text-sm">{{ existingPetInfo.pet_allergies }}</p>
                                    </div>
                                </div>
                            </div>

                            <!-- Multiple Pets Form -->
                            <template v-else>
                                <div v-for="(pet, index) in pets" :key="index" class="mb-6 p-4 border rounded-lg space-y-4">
                                    <div class="flex items-center justify-between mb-4">
                                        <h4 class="font-semibold text-base">Pet {{ index + 1 }}</h4>
                                        <Button 
                                            v-if="pets.length > 1"
                                            type="button" 
                                            variant="ghost" 
                                            size="sm"
                                            @click="removePet(index)"
                                            class="text-destructive hover:text-destructive"
                                        >
                                            <Trash2 class="h-4 w-4 mr-2" />
                                            Remove
                                        </Button>
                                    </div>

                                    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                                        <div class="space-y-2">
                                            <Label :for="`pet_type_id_${index}`">Pet Type <span class="text-destructive">*</span></Label>
                                            <SearchableSelect
                                                :id="`pet_type_id_${index}`"
                                                v-model="pet.pet_type_id"
                                                :options="petTypeOptions"
                                                placeholder="Select Pet Type"
                                                search-placeholder="Search pet types..."
                                                :required="true"
                                                :allow-create="true"
                                                create-prefix="Add new type"
                                                :custom-value="pet.customPetTypeDisplay"
                                                @update:custom-value="(val) => pet.customPetTypeDisplay = val"
                                                @create="(name) => handleCreatePetType(index, name)"
                                            />
                                            <p v-if="pet.customPetTypeDisplay" class="text-xs text-blue-600">
                                                New pet type "{{ pet.customPetTypeDisplay }}" will be created when you submit the form.
                                            </p>
                                            <InputError v-if="petErrors[index]?.pet_type_id" :message="petErrors[index].pet_type_id" />
                                        </div>

                                        <div class="space-y-2">
                                            <Label :for="`pet_name_${index}`">Pet Name</Label>
                                            <Input
                                                :id="`pet_name_${index}`"
                                                v-model="pet.pet_name"
                                                type="text"
                                                placeholder="e.g., Max, Bella"
                                                autocomplete="off"
                                            />
                                        </div>

                                        <div class="space-y-2">
                                            <Label :for="`pet_breed_${index}`">Pet Breed <span class="text-destructive">*</span></Label>
                                            <SearchableSelect
                                                :id="`pet_breed_${index}`"
                                                v-model="pet.pet_breed"
                                                :options="getBreedOptions(index)"
                                                placeholder="Select Pet Breed"
                                                search-placeholder="Search breeds..."
                                                :required="true"
                                                :disabled="!getSelectedPetTypeName(index) && !pet.customPetTypeDisplay"
                                                :allow-create="!!getSelectedPetTypeName(index) || !!pet.customPetTypeDisplay"
                                                create-prefix="Add new breed"
                                                :custom-value="pet.customBreedDisplay"
                                                @update:custom-value="(val) => pet.customBreedDisplay = val"
                                                @create="(name) => handleCreateBreed(index, name)"
                                            />
                                            <p v-if="pet.customBreedDisplay" class="text-xs text-blue-600">
                                                New breed "{{ pet.customBreedDisplay }}" will be created when you submit the form.
                                            </p>
                                            <InputError v-if="petErrors[index]?.pet_breed" :message="petErrors[index].pet_breed" />
                                        </div>

                                        <div class="space-y-2">
                                            <Label :for="`pet_gender_${index}`">Pet Gender</Label>
                                            <select
                                                :id="`pet_gender_${index}`"
                                                v-model="pet.pet_gender"
                                                class="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                                            >
                                                <option value="">Select Gender</option>
                                                <option value="Male">Male</option>
                                                <option value="Female">Female</option>
                                            </select>
                                        </div>

                                        <div class="space-y-2">
                                            <Label :for="`pet_birth_date_${index}`">Pet Birth Date</Label>
                                            <Input
                                                :id="`pet_birth_date_${index}`"
                                                v-model="pet.pet_birth_date"
                                                type="date"
                                                autocomplete="off"
                                            />
                                        </div>
                                    </div>

                                    <div class="space-y-2">
                                        <Label :for="`pet_allergies_${index}`">Pet Allergies</Label>
                                        <Input
                                            :id="`pet_allergies_${index}`"
                                            v-model="pet.pet_allergies"
                                            type="text"
                                            placeholder="e.g., Peanuts, Pollen"
                                            autocomplete="off"
                                        />
                                    </div>
                                </div>
                            </template>
                        </div>

                        <div class="flex justify-end gap-4">
                            <Link href="/admin/walk_in_clients">
                                <Button type="button" variant="outline">Cancel</Button>
                            </Link>
                            <Button type="button" @click="goToVisitDetails">
                                Next
                            </Button>
                        </div>
                    </Form>

                    <!-- Step 3: Visit Details -->
                    <Form v-else-if="currentStep === 'visitDetails'" @submit.prevent="submit" class="space-y-6">
                        <div class="flex items-center justify-between mb-4 pb-4 border-b">
                            <h3 class="text-lg font-semibold">Visit Details</h3>
                            <Button type="button" variant="ghost" size="sm" @click="goBackToForm">
                                <ArrowLeft class="h-4 w-4 mr-2" />
                                Back
                            </Button>
                        </div>

                        <div class="space-y-4">
                            <div>
                                <h4 class="text-base font-semibold mb-4">Select Pet(s) and Appointment Type(s)</h4>
                                
                                <!-- Existing Pet Display -->
                                <div v-if="existingPetSelected && existingPetInfo" class="border rounded-lg overflow-hidden">
                                    <div class="overflow-x-auto">
                                        <table class="w-full border-collapse">
                                            <thead class="sticky top-0 bg-muted/50 z-10 backdrop-blur-sm">
                                                <tr class="border-b">
                                                    <th class="text-left p-3 font-semibold text-sm">Pet</th>
                                                    <th
                                                        v-for="appointmentType in appointmentTypeOptions"
                                                        :key="appointmentType.value"
                                                        class="text-center p-3 font-semibold text-sm"
                                                    >
                                                        {{ appointmentType.label }}
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr class="border-b hover:bg-muted/30">
                                                    <td class="p-3 font-medium text-sm">
                                                        {{ existingPetInfo.pet_name || 'Pet' }}
                                                        <span class="text-muted-foreground">
                                                            ({{ existingPetInfo.pet_type }})
                                                        </span>
                                                    </td>
                                                    <td
                                                        v-for="appointmentType in appointmentTypeOptions"
                                                        :key="appointmentType.value"
                                                        class="p-3 text-center"
                                                    >
                                                        <input
                                                            type="checkbox"
                                                            :id="`checkbox_existing_${appointmentType.value}`"
                                                            :checked="isCheckboxSelected('0', appointmentType.value)"
                                                            @change="toggleCheckbox('0', appointmentType.value)"
                                                            class="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary cursor-pointer"
                                                        />
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                <!-- New Pets Display -->
                                <div v-else-if="pets.length === 0" class="text-center py-8 border-2 border-dashed rounded-lg">
                                    <p class="text-sm text-muted-foreground">No pets registered. Please go back and add at least one pet.</p>
                                </div>

                                <div v-else class="border rounded-lg overflow-hidden">
                                    <div class="overflow-x-auto">
                                        <table class="w-full border-collapse">
                                            <thead class="sticky top-0 bg-muted/50 z-10 backdrop-blur-sm">
                                                <tr class="border-b">
                                                    <th class="text-left p-3 font-semibold text-sm">Pet</th>
                                                    <th
                                                        v-for="appointmentType in appointmentTypeOptions"
                                                        :key="appointmentType.value"
                                                        class="text-center p-3 font-semibold text-sm"
                                                    >
                                                        {{ appointmentType.label }}
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr
                                                    v-for="(pet, index) in pets"
                                                    :key="index"
                                                    class="border-b hover:bg-muted/30"
                                                >
                                                    <td class="p-3 font-medium text-sm">
                                                        {{ pet.pet_name || `Pet ${index + 1}` }}
                                                        <span v-if="pet.pet_type_id" class="text-muted-foreground">
                                                            ({{ props.pet_types.find(pt => pt.id.toString() === pet.pet_type_id)?.name || 'Unknown' }})
                                                        </span>
                                                    </td>
                                                    <td
                                                        v-for="appointmentType in appointmentTypeOptions"
                                                        :key="appointmentType.value"
                                                        class="p-3 text-center"
                                                    >
                                                        <input
                                                            type="checkbox"
                                                            :id="`checkbox_${index}_${appointmentType.value}`"
                                                            :checked="isCheckboxSelected(index.toString(), appointmentType.value)"
                                                            @change="toggleCheckbox(index.toString(), appointmentType.value)"
                                                            class="h-4 w-4 rounded border-gray-300 text-primary focus:ring-primary cursor-pointer"
                                                        />
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                <p class="text-xs sm:text-sm text-muted-foreground mt-4">
                                    Select one or more appointment types for each pet by checking the boxes. You can select multiple pets and multiple appointment types.
                                </p>
                                <InputError v-if="form.errors.pets" :message="form.errors.pets" />
                            </div>

                            <div class="space-y-2">
                                <Label for="symptoms">Symptoms / Notes</Label>
                                <textarea
                                    id="symptoms"
                                    v-model="symptoms"
                                    rows="3"
                                    class="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                                    placeholder="Describe any symptoms or notes for this appointment..."
                                ></textarea>
                                <InputError :message="form.errors.symptoms" />
                            </div>
                        </div>

                        <div class="flex justify-end gap-4">
                            <Link href="/admin/walk_in_clients">
                                <Button type="button" variant="outline">Cancel</Button>
                            </Link>
                            <Button type="submit" :disabled="form.processing || !canProceedToSubmit">
                                Approve
                            </Button>
                        </div>
                    </Form>
                </CardContent>
            </Card>
        </div>
    </AppLayout>
</template>

